### ISSUE TITLE
こたつでたこぱ

### ISSUE THREAD

**Issue by n4mlz** [n4mlz/Life-public#1]
## summary
うちにこたつとたこ焼き器がデプロイされたので、こたつでたこパしませんか👀

## requirements

- 最大8人
- こたつ: 4 席
- テーブル: 4 席

**Comment by Ryoga-exe** [comment]
たこ焼き、焼いたことあります

**Comment by n4mlz** [comment]
Ryogaママ assigned

**Comment by n4mlz** [comment]
ん、これ誰かがなんかここにコメントしないと assign できないの？suggestion が Ryoga しかでてこない

**Comment by Ryoga-exe** [comment]
実は: はい

メンションしたらできるかもしれんな、よくわかっていません

**Comment by n4mlz** [comment]
@WhatACotton
@Yu212

**Comment by n4mlz** [comment]
かわりませんでした

**Comment by Yu212** [comment]
🤛👀🤜

**Comment by n4mlz** [comment]
できた

**Comment by n4mlz** [comment]
テスト後にしようと思うのですが、どうですか？テスト期間でもいいが

**Comment by arata-nvm** [comment]
👀

**Comment by rqdaA** [comment]
たこ焼きを焼くのが上手だと自認してます

**Comment by s7tya** [comment]
🖐️

**Comment by n4mlz** [comment]
皆さん、25日はどうでしょう！！！
リアクションください👋
